HSMedicalJournalsDB/Models/Journal.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web.Mvc;

namespace HSMedicalJournalsDB.Models
{
    public class Journal
    {       
        public Journal()
        {
            PublicationDate = DateTime.Now;
            Publisher = new User();
            Category = new Category();
            Editorial = new Editorial();
        }

        [HiddenInput(DisplayValue = false)]
        public int Id { get; set; }

        [Required]
        [Display(Name = "Name")]
        [StringLength(50)]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Description")]
        public string Description { get; set; }

        [Required]
        public User Publisher { get; set; }

        [Required]
        public double Price { get; set; }

        [Required]
        [Display(Name = "Editor")]
        [StringLength(50)]
        public string Editor { get; set; }

        [Required]
        public Editorial Editorial { get; set; }

        [Required]
        public Category Category { get; set; }

        [Required]
        [Display(Name = "Language")]
        [StringLength(20)]
        public string Language { get; set; }

        [Required]
        public string FilePath { get; set; }                
        
        [Required]
        public DateTime PublicationDate { get; set; }
    }
}

HSMedicalJournalsDB/Controllers/JournalController.cs
using HSMedicalJournalsDB.Models;
using HSMedicalJournalsDB.Security;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HSMedicalJournalsDB.Controllers
{
    public class JournalController : Controller
    {
        string strConn = "Data Source=(LocalDb)\\MSSQLLocalDB;Initial Catalog=HSMedicalJournalsDB;Integrated Security=True";

        // GET: Journal
        public ActionResult GetAll()
        {
            if (Session["userId"] != null)
            {
                using (HSContext db = new HSContext())
                {
                    return View(db.Journals.ToList());
                }         
            }
            else
            {
                return RedirectToAction("Index", "Home", new { area = "" });
            }
        }

        public ActionResult GetById(string username)
        {

            if (Session["userId"] != null)
            {
                using (HSContext db = new HSContext())
                {
                    return PartialView(db.Journals.Where(j => j.Publisher.UserName == username).ToList());
                }
            }else
            {
                return RedirectToAction("Index", "Home", new { area = "" });
            }
        }

        public ActionResult UploadFile()
        {
            if (Session["userId"] != null)
            {
                return View();               
            }
            else
            {
                return RedirectToAction("Index", "Home", new { area = "" });
            }
        }

        [HttpPost]
        public ActionResult UploadFile(HttpPostedFileBase file)
        {
            if (Session["userId"] != null)
            {
                if (file != null)
                {
                    TempData["fileToUpload"] = file;

                    return RedirectToAction("UploadDescription", new { area = "" });
                }else
                {
                    return View();
                }
            }else
            {
                return RedirectToAction("Index", "Home", new { area = "" });
            }
        }
        
        public ActionResult UploadDescription()
        {
            if (Session["userId"] != null)
            {
                HttpPostedFileBase file = (HttpPostedFileBase)TempData["fileToUpload"];

                if (file != null)
                {
                    HSContext db = new HSContext();
                    ViewBag.Categories = new SelectList(db.Categories, "Id", "Name");
                    ViewBag.Editorials = new SelectList(db.Editorials, "Id", "Name");
                    TempData["fileToUpload"] = file;
                    return View();
                }
                else
                {
                    return RedirectToAction("UploadFile", new { area = "" });
                }
            }
            else
            {
                return RedirectToAction("Index", "Home", new { area = "" });
            }                
        }

        [HttpPost]
        public ActionResult UploadDescription(Journal journal, FormCollection form)
        {
            if (Session["userId"] != null)
            {
                HttpPostedFileBase file = (HttpPostedFileBase)TempData["fileToUpload"];
                                
                string cat = form["Categories"].ToString();
                string edi = form["Editorials"].ToString();
                
                if (file == null)
                {
                    return RedirectToAction("UploadFile", new { area = "" });
                }
                else
                {
                    HSContext db = new HSContext();
                    
                    foreach (var user in db.Users)
                    {
                        if (user.UserName.Equals(Session["userName"].ToString()))
                        {
                            journal.Publisher = user;
                            break;
                        }
                    }

                    foreach (var category in db.Categories)
                    {
                        if (category.Id == int.Parse(cat))
                        {
                            journal.Category = category;
                            break;
                        }
                    }

                    foreach (var editorial in db.Editorials)
                    {
                        if (editorial.Id == int.Parse(edi))
                        {
                            journal.Editorial = editorial;
                            break;
                        }
                    }

                    string fileName = DateTime.Now.ToString("ddMMyyyyHHmmssfff");
                    string serverPath = Server.MapPath("~/Files/"+fileName+".pdf");                    
                    file.SaveAs(serverPath);
                    journal.FilePath = fileName;
                    
                    db.Journals.Add(journal);
                    db.SaveChanges();

                    db.Dispose();
                    return RedirectToAction("Index", "Home", new { area = "" });
                }                
            }
            else
            {
                return RedirectToAction("Index", "Home", new { area = "" });
            }
        }

        public ActionResult MySubscriptions()
        {
            if (Session["userId"] != null)
            {
                using (HSContext db = new HSContext())
                {
                    using (SqlConnection conn = new SqlConnection(strConn))
                    {
                        conn.Open();

                        string cadena = "select j.* from Journals as j left join Subscriptions as s on j.Id = s.Journal_Id " +
                                        "where s.User_Id = @1";
                        SqlCommand cmd = new SqlCommand(cadena, conn);
                        cmd.Parameters.AddWithValue("@1", int.Parse(Session["userId"].ToString()));
                        SqlDataAdapter da = new SqlDataAdapter(cmd);
                        DataSet ds = new DataSet();
                        da.Fill(ds);

                        List<Journal> journals = new List<Journal>();

                        if (ds.Tables[0].Rows.Count > 0)
                        {
                            for (int i = 0; i < ds.Tables[0].Rows.Count; i++)
                            {
                                Journal journal = new Journal();
                                journal.Id = (int)ds.Tables[0].Rows[i]["Id"];
                                journal.Name = ds.Tables[0].Rows[i]["Name"].ToString();
                                journal.Description = ds.Tables[0].Rows[i]["Description"].ToString();
                                journal.Price = (double)ds.Tables[0].Rows[i]["Price"];
                                journal.Editor = ds.Tables[0].Rows[i]["Editor"].ToString();
                                journal.Language = ds.Tables[0].Rows[i]["Language"].ToString();
                                journal.FilePath = ds.Tables[0].Rows[i]["FilePath"].ToString();
                                journal.PublicationDate = (DateTime)ds.Tables[0].Rows[i]["PublicationDate"];
                                journals.Add(journal);
                            }
                        }

                        return View(journals);
                    }
                }
            }
            else
            {
                return RedirectToAction("Index", "Home", new { area = "" });
            }
        }

        public ActionResult Subscribe()
        {
            if(Session["userId"] != null)
            {
                using (HSContext db = new HSContext())
                {
                    using (SqlConnection conn = new SqlConnection(strConn))
                    {
                        conn.Open();

                        string cadena = "select * from journals where Publisher_Id <> @1 and (Id not in (select Journal_Id from Subscriptions where User_Id = @1))";
                        
                        SqlCommand cmd = new SqlCommand(cadena, conn);
                        int uid = int.Parse(Session["userId"].ToString());
                        cmd.Parameters.AddWithValue("@1", int.Parse(Session["userId"].ToString()));

                        SqlDataAdapter da = new SqlDataAdapter(cmd);
                        DataSet ds = new DataSet();
                        da.Fill(ds);

                        List<Journal> journals = new List<Journal>();

                        if (ds.Tables[0].Rows.Count > 0)
                        {
                            for (int i = 0; i< ds.Tables[0].Rows.Count; i++)
                            {
                                Journal journal = new Journal();
                                journal.Id = (int)ds.Tables[0].Rows[i]["Id"];
                                journal.Name = ds.Tables[0].Rows[i]["Name"].ToString();
                                journal.Description = ds.Tables[0].Rows[i]["Description"].ToString();
                                journal.Price = (double)ds.Tables[0].Rows[i]["Price"];
                                journal.Editor = ds.Tables[0].Rows[i]["Editor"].ToString();
                                journal.Language = ds.Tables[0].Rows[i]["Language"].ToString();
                                journal.FilePath = ds.Tables[0].Rows[i]["FilePath"].ToString();
                                journal.PublicationDate = (DateTime)ds.Tables[0].Rows[i]["PublicationDate"];
                                journals.Add(journal);
                            }
                        }

                        return View(journals);
                    }
                }
            }
            else
            {
                return RedirectToAction("My", "Home", new { area = "" });

HSMedicalJournalsDB/Views/Journal/GetAll.cshtml
@model IEnumerable<HSMedicalJournalsDB.Models.Journal>

@{
    ViewBag.Title = "Publications";
}

<h2>All Publications</h2>

<p>
    @Html.ActionLink("Publish", "Upload")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Editor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Language)
        </th>
        
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Editor)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Language)
        </td>
    </tr>
}
</table>

HSMedicalJournalsDB/Views/Journal/GetById.cshtml
@model IEnumerable<HSMedicalJournalsDB.Models.Journal>

@{
    ViewBag.Title = "GetById";
}

<h2>My Publications</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Editor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Language)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FilePath)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PublicationDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Editor)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Language)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FilePath)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PublicationDate)
        </td>
        <td>
            @*@Html.ActionLink("View PDF", "ViewPdf", new { id=item.Id }) |*@            
            @Html.ActionLink("Delete", "DeletePublication", new { id=item.Id })
        </td>
    </tr>
}

</table>

HSMedicalJournalsDB/Views/Journal/MySubscriptions.cshtml
@model IEnumerable<HSMedicalJournalsDB.Models.Journal>

@{
    ViewBag.Title = "MySubscriptions";
}

<h3>Welcome @Session["userName"].ToString()</h3>

<h2>My Subscriptions</h2>

<p>
    @Html.ActionLink("Subscribe", "Subscribe")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Editor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Language)
        </th>        
        <th>
            @Html.DisplayNameFor(model => model.PublicationDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Editor)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Language)
        </td>       
        <td>
            @Html.DisplayFor(modelItem => item.PublicationDate)
        </td>
        <td>
            @Html.ActionLink("Cancel Subscription", "CancelSubscription", new { id=item.Id })
        </td>
    </tr>
}

</table>

<div>
    @Html.ActionLink("Back to Home", "Index", "Home")
</div>

HSMedicalJournalsDB/Views/Journal/Subscribe.cshtml
@model IEnumerable<HSMedicalJournalsDB.Models.Journal>

@{
    ViewBag.Title = "Subscribe";
}

<h3>Welcome @Session["userName"].ToString()</h3>

<h2>Select a Journal to subscribe</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Editor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Language)
        </th>        
        <th>
            @Html.DisplayNameFor(model => model.PublicationDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Editor)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Language)
        </td>        
        <td>
            @Html.DisplayFor(modelItem => item.PublicationDate)
        </td>
        <td>
            @Html.ActionLink("Subscribe", "ConfirmSubscription", new { id=item.Id })
        </td>
    </tr>
}

</table>

<div>
    @Html.ActionLink("Back to Home", "Index", "Home")
</div>

HSMedicalJournalsDB/Views/Journal/SubscribeConfirm.cshtml
@{
    ViewBag.Title = "SubscribeConfirm";
}

<h2>Are you sure to subscribe to this journal?</h2>

HSMedicalJournalsDB/Views/Journal/UploadDescription.cshtml
@model HSMedicalJournalsDB.Models.Journal

@{
    ViewBag.Title = "UploadDescription";
}

<h2>Journal Description</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Editor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Editor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Editor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Language, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Language, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Language, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category, "Category", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">                
                @Html.DropDownList("Categories", null, "Select a category",new { @class="form-control"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Editorial, "Editorial", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Editorials", null, "Select an editorial", new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Home", "Index", "Home")
</div>

HSMedicalJournalsDB/Views/Journal/UploadFile.cshtml
@{
    ViewBag.Title = "UploadFile";
}

<h2>Select a PDF file</h2>

@using (Html.BeginForm("UploadFile","Journal",FormMethod.Post,new { enctype = "multipart/form-data" }))
{
    <input type="file" name="file" id="file" accept="application/pdf" />

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Next" class="btn btn-default" />
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Home", "Index", "Home")
</div>